spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=esunbank;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true